### ISSUE TITLE
Unhandled exception updating baseline before any sensor readings.

### ISSUE THREAD

**Issue by malcpps** [SingleTact/NETInterface#1]
SingleTactDemo.exe v1.0.0.0 dated 22 Jun 2016, running on Windows 10 (64 bit).

To reproduce: Start program with no Arduino connected.  When the 'Invalid Settings' warning appears, click OK.  Click 'Update Baseline'.

Here is a screenshot, plus the exception text:

![std-crash](https://cloud.githubusercontent.com/assets/19389579/21226808/14490eec-c2cf-11e6-9ee8-84bf494794ad.PNG)

System.NullReferenceException: Object reference not set to an instance of an object.
   at SingleTactLibrary.SingleTact.Tare() in C:\Users\ppsuser\Documents\PPS-Code\NETInterface\SingleTactLibrary\SingleTact.cs:line 195
   at SingleTact_Demo.GUI.SetBaselineButton_Click(Object sender, EventArgs e) in C:\Users\Malcolm\Documents\GitHub\NETInterface\SingleTact Demo\GUI.cs:line 465
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by malcpps** [comment]
Assigned to Barnali to test the fix on master.

**Comment by malcpps** [comment]
The binaries to test are all attached to the [release page](https://github.com/SingleTact/NETInterface/releases/tag/v1.1.0-rc).

**Comment by Barnali-Das** [comment]
The problem is Fixed.
Start program with no Arduino connected. The Demo software screen doesn't appear now showing the message 'Hardware initialisation failed'.

![image](https://cloud.githubusercontent.com/assets/5993394/26054875/492850c4-3966-11e7-9455-70b03995452c.png)
